/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ATM;

/**
 *
 * @author huyduong
 */
public class FastCashScreen extends javax.swing.JFrame {
    
    private Account bankAccount;
    
    private javax.swing.JPanel $$$1;
    private javax.swing.JLabel $label;
    private javax.swing.JLabel ATMLabel3;
    private javax.swing.JPanel ATMLogo3;
    private javax.swing.JLabel accountText;
    private javax.swing.JButton eightyButton;
    private javax.swing.JLabel fastcashText;
    private javax.swing.JButton fortyButton;
    private java.awt.Button homeButton;
    private javax.swing.JButton hundredButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel message;
    private javax.swing.JPanel screen7;
    private java.awt.Button signoutButton;
    private javax.swing.JButton sixtyButton;
    private javax.swing.JButton twentyButton;
    private javax.swing.JButton twohundredButton;
    private javax.swing.JLabel welcomeText;

    /**
     * Creates new form FastCashScreen
     */
    public FastCashScreen(Account acc) {
        super();
        bankAccount = acc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                     
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ATMLogo3 = new javax.swing.JPanel();
        ATMLabel3 = new javax.swing.JLabel();
        screen7 = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        accountText = new javax.swing.JLabel();
        signoutButton = new java.awt.Button();
        homeButton = new java.awt.Button();
        fastcashText = new javax.swing.JLabel();
        fortyButton = new javax.swing.JButton();
        hundredButton = new javax.swing.JButton();
        sixtyButton = new javax.swing.JButton();
        twentyButton = new javax.swing.JButton();
        twohundredButton = new javax.swing.JButton();
        eightyButton = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        $$$1 = new javax.swing.JPanel();
        $label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        ATMLogo3.setBackground(new java.awt.Color(255, 255, 255));

        ATMLabel3.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 48)); // NOI18N
        ATMLabel3.setForeground(new java.awt.Color(0, 102, 51));
        ATMLabel3.setText("ATM");

        javax.swing.GroupLayout ATMLogo3Layout = new javax.swing.GroupLayout(ATMLogo3);
        ATMLogo3.setLayout(ATMLogo3Layout);
        ATMLogo3Layout.setHorizontalGroup(
            ATMLogo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ATMLogo3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ATMLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        ATMLogo3Layout.setVerticalGroup(
            ATMLogo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ATMLogo3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(ATMLabel3)
                .addContainerGap())
        );

        screen7.setBackground(new java.awt.Color(255, 255, 255));

        welcomeText.setFont(new java.awt.Font("Monospaced", 1, 30)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(0, 51, 204));
        welcomeText.setText("THE BANK");

        accountText.setFont(new java.awt.Font("SansSerif", 2, 13)); // NOI18N
        accountText.setForeground(new java.awt.Color(102, 102, 102));
        accountText.setText("Account Number: xxxxxxxxxxxx");

        signoutButton.setBackground(new java.awt.Color(255, 96, 96));
        signoutButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        signoutButton.setForeground(new java.awt.Color(255, 255, 255));
        signoutButton.setLabel("Sign Out");
        signoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(123, 166, 253));
        homeButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setLabel("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        fastcashText.setBackground(new java.awt.Color(0, 102, 51));
        fastcashText.setFont(new java.awt.Font(".AppleSystemUIFont", 3, 24)); // NOI18N
        fastcashText.setForeground(new java.awt.Color(0, 102, 51));
        fastcashText.setText("Fast Cash");

        fortyButton.setBackground(new java.awt.Color(0, 102, 51));
        fortyButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        fortyButton.setForeground(new java.awt.Color(255, 255, 255));
        fortyButton.setText("$40");
        fortyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fortyButtonActionPerformed(evt);
            }
        });

        hundredButton.setBackground(new java.awt.Color(0, 102, 51));
        hundredButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        hundredButton.setForeground(new java.awt.Color(255, 255, 255));
        hundredButton.setText("$100");
        hundredButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hundredButtonActionPerformed(evt);
            }
        });

        sixtyButton.setBackground(new java.awt.Color(0, 102, 51));
        sixtyButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        sixtyButton.setForeground(new java.awt.Color(255, 255, 255));
        sixtyButton.setText("$60");
        sixtyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixtyButtonActionPerformed(evt);
            }
        });

        twentyButton.setBackground(new java.awt.Color(0, 102, 51));
        twentyButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        twentyButton.setForeground(new java.awt.Color(255, 255, 255));
        twentyButton.setText("$20");
        twentyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyButtonActionPerformed(evt);
            }
        });

        twohundredButton.setBackground(new java.awt.Color(0, 102, 51));
        twohundredButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        twohundredButton.setForeground(new java.awt.Color(255, 255, 255));
        twohundredButton.setText("$200");
        twohundredButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twohundredButtonActionPerformed(evt);
            }
        });

        eightyButton.setBackground(new java.awt.Color(0, 102, 51));
        eightyButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        eightyButton.setForeground(new java.awt.Color(255, 255, 255));
        eightyButton.setText("$80");
        eightyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightyButtonActionPerformed(evt);
            }
        });

        message.setFont(new java.awt.Font("SansSerif", 2, 13)); // NOI18N
        message.setForeground(new java.awt.Color(102, 102, 102));
        message.setText("Withdrawing cash...");

        javax.swing.GroupLayout screen7Layout = new javax.swing.GroupLayout(screen7);
        screen7.setLayout(screen7Layout);
        screen7Layout.setHorizontalGroup(
            screen7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screen7Layout.createSequentialGroup()
                .addGroup(screen7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(screen7Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(welcomeText))
                    .addGroup(screen7Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(accountText))
                    .addGroup(screen7Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(fastcashText))
                    .addGroup(screen7Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(screen7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hundredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sixtyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twentyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(screen7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fortyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twohundredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eightyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, screen7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(message)
                .addGap(197, 197, 197))
        );
        screen7Layout.setVerticalGroup(
            screen7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screen7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(welcomeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fastcashText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(screen7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fortyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twentyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(screen7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixtyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(screen7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hundredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twohundredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(screen7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        $$$1.setBackground(new java.awt.Color(21, 120, 17));

        $label.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        $label.setForeground(new java.awt.Color(255, 255, 255));
        $label.setText("$$$");

        javax.swing.GroupLayout $$$1Layout = new javax.swing.GroupLayout($$$1);
        $$$1.setLayout($$$1Layout);
        $$$1Layout.setHorizontalGroup(
            $$$1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup($$$1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent($label)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        $$$1Layout.setVerticalGroup(
            $$$1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent($label)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(screen7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ATMLogo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent($$$1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ATMLogo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(screen7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent($$$1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void signoutButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        dispose();
        new LoginScreen().launchLogin();;
    }                                             

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        dispose();
        new HomeScreen(bankAccount).launchHome();
    }                                          

    private void twentyButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void fortyButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void eightyButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void sixtyButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void hundredButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void twohundredButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /**
     * @param args the command line arguments
     */
    public void launchFastCash() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCashScreen(bankAccount).setVisible(true);
            }
        });
    }

}
